/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Userrole = "ADMIN" | "APPROVER" | "EXPORTER" | "STEWARD" | "VIEWER";

export interface _Migrations {
  applied_at: Generated<Timestamp>;
  filename: string;
}

export interface AuditEvents {
  action: string;
  actor_user_id: string | null;
  approval_ref: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: string;
  model_version: string | null;
  new_value: Json | null;
  old_value: Json | null;
  rule_version: string | null;
  tenant_id: string;
}

export interface Datasets {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  project_id: string;
  tenant_id: string;
  updated_at: Timestamp;
}

export interface DatasetVersions {
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  dataset_id: string;
  id: string;
  parent_version_id: string | null;
  row_count: number | null;
  source_artifact_checksum: string;
  source_artifact_ref: string;
  status: Generated<string>;
  tenant_id: string;
  version_number: number;
}

export interface Policies {
  created_at: Generated<Timestamp>;
  id: string;
  key: string;
  tenant_id: string;
  updated_at: Timestamp;
  value: Json;
}

export interface Projects {
  created_at: Generated<Timestamp>;
  domain: string;
  environment: Generated<string>;
  id: string;
  milestone: string | null;
  name: string;
  owner_user_id: string;
  source_system: string;
  status: Generated<string>;
  target_system: string;
  tenant_id: string;
  updated_at: Timestamp;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  updated_at: Timestamp;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string;
  id: string;
  role: Generated<Userrole>;
  tenant_id: string;
  updated_at: Timestamp;
}

export interface DB {
  _migrations: _Migrations;
  audit_events: AuditEvents;
  dataset_versions: DatasetVersions;
  datasets: Datasets;
  policies: Policies;
  projects: Projects;
  tenants: Tenants;
  users: Users;
}
